// src/Changepassword.jsx
import React, { useState } from "react";
import axios from "axios";
import { useNavigate } from "react-router-dom";
import "./css/Login.css";

const ChangePassword = () => {
  const [email, setEmail] = useState("");
  const [emailVerified, setEmailVerified] = useState(false);
  const [newPassword, setNewPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [redirectCountdown, setRedirectCountdown] = useState(3);
  const [showRedirectLoader, setShowRedirectLoader] = useState(false);
  const [showEmailLoader, setShowEmailLoader] = useState(false);
  const [emailCountdown, setEmailCountdown] = useState(3);
  const [alertMessage, setAlertMessage] = useState(""); // ✅ Alert msg
  const [alertType, setAlertType] = useState(""); // success | danger
  const navigate = useNavigate();

  // Step 1: Email Verification
  const handleEmailSubmit = async (e) => {
    e.preventDefault();
    setShowEmailLoader(true);
    setAlertMessage(""); // Clear old alerts

    try {
      const res = await axios.post("https://backend-t19q.onrender.com/verify-email", {
        email: email.toLowerCase(),
      });

      if (res.data.exists) {
        setAlertMessage("✅ Email verified. Enter new password.");
        setAlertType("success");

        const countdown = setInterval(() => {
          setEmailCountdown((prev) => {
            if (prev === 1) {
              clearInterval(countdown);
              setEmailVerified(true);
              setShowEmailLoader(false);
            }
            return prev - 1;
          });
        }, 1000);
      } else {
        setAlertMessage("❌ Email not found.");
        setAlertType("danger");
        setShowEmailLoader(false);
      }
    } catch (err) {
      console.error(err);
      setAlertMessage("Server error during email verification.");
      setAlertType("danger");
      setShowEmailLoader(false);
    }
  };

  // Step 2: Password Change
  const handlePasswordChange = async (e) => {
    e.preventDefault();
    setAlertMessage(""); // Clear old alerts

    if (newPassword !== confirmPassword) {
      setAlertMessage("❌ Passwords do not match.");
      setAlertType("danger");
      return;
    }

    try {
      const res = await axios.post("https://backend-t19q.onrender.com/change-password", {
        email: email.toLowerCase(),
        newPassword,
      });

      if (res.data.message === "Password updated successfully ✅") {
        setAlertMessage("✅ Password updated successfully.");
        setAlertType("success");
        setShowRedirectLoader(true);

        const countdown = setInterval(() => {
          setRedirectCountdown((prev) => {
            if (prev === 1) {
              clearInterval(countdown);
              navigate("/login");
            }
            return prev - 1;
          });
        }, 1000);
      } else {
        setAlertMessage(res.data.message);
        setAlertType("danger");
      }
    } catch (err) {
      console.error(err);
      setAlertMessage("Server error during password change.");
      setAlertType("danger");
    }
  };

  return (
    <div className="body">
      <div className="container d-flex justify-content-center align-items-center vh-100">
        <div className="login-container">
          <h2 className="text-success text-center mb-3 h2">
            Change Password
          </h2>
          <hr />

          {/* ✅ Alert Message */}
          {alertMessage && (
            <div className={`alert alert-${alertType}`} role="alert">
              {alertMessage}
            </div>
          )}

          {/* ✅ Form and Loaders */}
          {!emailVerified && !showEmailLoader ? (
            <form onSubmit={handleEmailSubmit}>
              <div className="mb-3">
                <label className="l1">Email</label>
                <input
                  type="email"
                  className="form-control mt-2"
                  placeholder="example@gmail.com"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  autoComplete="off"
                  autoCapitalize="words"
                  autoCorrect="off"
                  spellCheck={false}
                  required
                />
              </div>
            <button type="submit" className="btn7 fw-bold w-100 rounded">
                Verify Email
              </button>
            </form>
          ) : showEmailLoader ? (
            <div className="text-center mt-4">
              <div className="spinner-border text-success" role="status"></div>
              <p className="mt-2">Verifying Email... {emailCountdown}</p>
            </div>
          ) : !showRedirectLoader ? (
            <form onSubmit={handlePasswordChange}>
              <div className="mb-2">
                <label className="mb-2 l1">New Password</label>
                <input
                  type="password"
                  className="form-control "
                  value={newPassword}
                  onChange={(e) => setNewPassword(e.target.value)}
                  placeholder="********"
                  required
                />
              </div>
              <div className="mb-3">
                <label className="mb-2 l1">Confirm Password</label>
                <input
                  type="password"
                  className="form-control "
                  value={confirmPassword}
                  onChange={(e) => setConfirmPassword(e.target.value)}
                  placeholder="********"
                  required
                />
              </div>
            <button type="submit" className="btn7 fw-bold w-100 rounded">
                Change Password
              </button>
            </form>
          ) : (
            <div className="text-center mt-4">
              <div className="spinner-border text-primary" role="status"></div>
              <p className="mt-2">Please Wait {redirectCountdown}...</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default ChangePassword;

// src/app/pages/change-password.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-change-password',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  templateUrl: './change-password.component.html',
  styleUrls: ['./login.component.css']
})
export class ChangePasswordComponent {
  email: string = "";
  emailVerified: boolean = false;
  newPassword: string = "";
  confirmPassword: string = "";
  redirectCountdown: number = 3;
  showRedirectLoader: boolean = false;
  showEmailLoader: boolean = false;
  emailCountdown: number = 3;
  alertMessage: string = "";
  alertType: string = "";

  constructor(private router: Router, private http: HttpClient) {}

  handleEmailSubmit() {
    if (!this.email) {
      this.alertMessage = "❌ Please enter your email.";
      this.alertType = "danger";
      return;
    }

    this.showEmailLoader = true;
    this.alertMessage = "";
    this.emailVerified = false;
    this.emailCountdown = 3;

    this.http.post<any>("https://backend-l22j.onrender.com/api/user/verify-email", {
      email: this.email.toLowerCase(),
    }).subscribe({
      next: (res) => {
        if (res.exists) {
          this.alertMessage = "✅ Email verified. Enter new password.";
          this.alertType = "success";

          const countdown = setInterval(() => {
            this.emailCountdown--;
            if (this.emailCountdown <= 0) {
              clearInterval(countdown);
              this.emailVerified = true;
              this.showEmailLoader = false;
            }
          }, 1000);
        } else {
          this.alertMessage = "❌ Email not found.";
          this.alertType = "danger";
          this.showEmailLoader = false;
        }
      },
      error: (err) => {
        console.error(err);
        this.alertMessage = "Server error during email verification.";
        this.alertType = "danger";
        this.showEmailLoader = false;
      }
    });
  }

  handlePasswordChange() {
    this.alertMessage = "";

    if (!this.newPassword || !this.confirmPassword) {
      this.alertMessage = "❌ Please fill in all password fields.";
      this.alertType = "danger";
      return;
    }

    if (this.newPassword.length < 8) {
      this.alertMessage = "❌ Password must be at least 8 characters.";
      this.alertType = "danger";
      return;
    }

    if (this.newPassword !== this.confirmPassword) {
      this.alertMessage = "❌ Passwords do not match.";
      this.alertType = "danger";
      return;
    }

    this.showRedirectLoader = false; // Ensure it's false before starting
    this.redirectCountdown = 3;

    this.http.post<any>("https://backend-l22j.onrender.com/api/user/change-password", {
      email: this.email.toLowerCase(),
      newPassword: this.newPassword,
    }).subscribe({
      next: (res) => {
        if (res.message === "Password updated successfully ✅") {
          this.alertMessage = "✅ Password updated successfully.";
          this.alertType = "success";
          this.showRedirectLoader = true;

          const countdown = setInterval(() => {
            this.redirectCountdown--;
            if (this.redirectCountdown <= 0) {
              clearInterval(countdown);
              this.router.navigate(["/login"]);
            }
          }, 1000);
        } else {
          this.alertMessage = res.message;
          this.alertType = "danger";
          this.showRedirectLoader = false;
        }
      },
      error: (err) => {
        console.error(err);
        this.alertMessage = "Server error during password change.";
        this.alertType = "danger";
        this.showRedirectLoader = false;
      }
    });
  }
}

<div class="body">
  <div class="container d-flex justify-content-center align-items-center vh-100">
    <div class="login-container">
      <h2 class="text-success text-center mb-3 h2">
        Change Password
      </h2>
      <hr />

      <div *ngIf="alertMessage" class="alert alert-{{alertType}}" role="alert">
        {{alertMessage}}
      </div>

      <ng-container *ngIf="!emailVerified && !showEmailLoader">
        <form (submit)="handleEmailSubmit()">
          <div class="mb-3">
            <label class="l1">Email</label>
            <input
              type="email"
              name="email"
              class="form-control mt-2"
              placeholder="example@gmail.com"
              [(ngModel)]="email"
              autocomplete="off"
              autocapitalize="words"
              autocorrect="off"
              [spellcheck]="false"
              required
            />
          </div>
          <button type="submit" class="btn7 fw-bold w-100 rounded">
            Verify Email
          </button>
        </form>
      </ng-container>

      <ng-container *ngIf="showEmailLoader">
        <div class="text-center mt-4">
          <div class="spinner-border text-success" role="status"></div>
          <p class="mt-2">Verifying Email... {{emailCountdown}}</p>
        </div>
      </ng-container>

      <ng-container *ngIf="emailVerified && !showRedirectLoader">
        <form (submit)="handlePasswordChange()">
          <div class="mb-2">
            <label class="mb-2 l1">New Password</label>
            <input
              type="password"
              name="newPassword"
              class="form-control"
              [(ngModel)]="newPassword"
              placeholder="********"
              required
            />
          </div>
          <div class="mb-3">
            <label class="mb-2 l1">Confirm Password</label>
            <input
              type="password"
              name="confirmPassword"
              class="form-control"
              [(ngModel)]="confirmPassword"
              placeholder="********"
              required
            />
          </div>
          <button type="submit" class="btn7 fw-bold w-100 rounded">
            Change Password
          </button>
        </form>
      </ng-container>

      <ng-container *ngIf="showRedirectLoader">
        <div class="text-center mt-4">
          <div class="spinner-border text-success" role="status"></div>
          <p class="mt-2">Please Wait {{redirectCountdown}}...</p>
        </div>
      </ng-container>
    </div>
  </div>
</div>
