// src/Checkout.jsx
import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import "./css/cart.css";

const Check = () => {
  const navigate = useNavigate();

  const [formData, setFormData] = useState({
    email: "",
    phone: "",
    countryCode: "+91",
    address: "",
    paymentMethod: "Cash On Delivery",
    cardNumber: "",
    expiry: "",
    cvv: "",
  });

  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState("");

  useEffect(() => {
    const fetchUserProfile = async () => {
      const token = localStorage.getItem("token");
      if (!token) return;

      try {
        const res = await axios.get("https://backend-t19q.onrender.com/user/profile", {
          headers: { Authorization: `Bearer ${token}` },
        });
        setFormData((prev) => ({
          ...prev,
          email: res.data.email || "",
          phone: res.data.phone || "",
        }));
      } catch (err) {
        console.error("Error fetching profile", err);
      }
    };

    fetchUserProfile();
  }, []);

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({ ...prev, [name]: value }));
  };

  // Luhn algorithm implementation
  const luhnCheck = (numStr) => {
    // numStr should be only digits (no spaces)
    let sum = 0;
    let shouldDouble = false;
    // process digits right-to-left
    for (let i = numStr.length - 1; i >= 0; i--) {
      let digit = parseInt(numStr.charAt(i), 10);
      if (shouldDouble) {
        digit = digit * 2;
        if (digit > 9) digit -= 9;
      }
      sum += digit;
      shouldDouble = !shouldDouble;
    }
    return sum % 10 === 0;
  };

const placeOrder = async (e) => {
  e.preventDefault();

  const rawCardNumber = formData.cardNumber.replace(/\s/g, "");

  if (formData.paymentMethod === "Online Payment") {
    // Basic length check — many cards are 13-19 digits, but most common are 16.
    if (rawCardNumber.length < 13 || rawCardNumber.length > 19) {
      alert(" Invalid card number — it should be between 13 and 19 digits.");
      return;
    }

    // ensure only digits
    if (!/^\d+$/.test(rawCardNumber)) {
      alert(" Card number must contain only digits.");
      return;
    }

    // Luhn validation
    if (!luhnCheck(rawCardNumber)) {
      alert("Invalid card number. Please enter a valid card.");
      return;
    }

    if (!/^\d{2}\/\d{2}$/.test(formData.expiry)) {
      alert(" Expiry must be in MM/YY format.");
      return;
    }

    // ---- Expiry Validation ----
    const [mm, yy] = formData.expiry.split("/");
    const month = parseInt(mm, 10);
    const year = parseInt("20" + yy, 10);

    if (month < 1 || month > 12) {
      alert("Invalid month.");
      return;
    }

    const now = new Date();
    const currentMonth = now.getMonth() + 1;
    const currentYear = now.getFullYear();

    if (year < currentYear) {
      alert("Card has expired.");
      return;
    }
    if (year === currentYear && month < currentMonth) {
      alert("Expiry month cannot be in the past.");
      return;
    }

    if (formData.cvv.length < 3) {
      alert("CVV must be at least 3 digits.");
      return;
    }
  }

  setLoading(true);
  setErrorMsg("");

  const token = localStorage.getItem("token");
  try {
    const payload = {
      ...formData,
      cardNumber: rawCardNumber,
    };

    await axios.post("https://backend-t19q.onrender.com/order", payload, {
      headers: { Authorization: `Bearer ${token}` },
    });

    navigate("/order-success");
  } catch (err) {
    console.error("Order failed", err);
    setErrorMsg("❌ Order failed. Please try again.");
  } finally {
    setLoading(false);
  }
};

  return (
    <div className="container py-4">
      <div className="row justify-content-center">
        <div className="col-lg-7 col-md-8">
          <div className="card shadow-lg border-0 p-4 rounded-4">
            <h1 className="fs-3 text-success text-center fw-bold checkout-title">
              Payment
            </h1>
            <p className="text-success fw-bold text-center checkout-subtitle">
              Brew & Pay • Easy Checkout
            </p>
            <hr />
            {errorMsg && (
              <div className="alert alert-danger py-2">{errorMsg}</div>
            )}

            <form onSubmit={placeOrder}>
              {/* Email + Phone */}
              <div className="mb-3 d-flex flex-column flex-sm-row gap-3">
                <div className="d-flex flex-column flex-fill">
                  <label className="form-label fw-semibold">Email ID</label>
                  <input
                    type="email"
                    name="email"
                    className="form-control form-control-lg rounded-3"
                    value={formData.email}
                    readOnly
                    required
                  />
                </div>
                <div className="d-flex flex-column flex-fill">
                  <label className="form-label fw-semibold">Phone Number</label>
                  <div className="input-group">
                    <select
                      className="form-select"
                      value={formData.countryCode}
                      style={{ maxWidth: "100px", height: "50px" }}
                      disabled
                    >
                      <option value="+91">+91 🇮🇳</option>
                    </select>
                    <input
                      type="tel"
                      name="phone"
                      className="form-control"
                      value={formData.phone}
                      readOnly
                      pattern="[0-9]{10}"
                      required
                    />
                  </div>
                </div>
              </div>

              {/* Address */}
              <div className="mb-3">
                <label className="form-label fw-semibold">
                  Shipping Address
                </label>
                <textarea
                  name="address"
                  className="form-control rounded-3"
                  placeholder="Enter your address"
                  style={{ resize: "none", height: "100px" }}
                  value={formData.address}
                  onChange={handleChange}
                  required
                ></textarea>
              </div>

               {/* Payment Method */}
              <div className="mb-3">
                <label className="form-label fw-semibold">Payment Method</label>
                <div className="mb-3 d-flex flex-column flex-sm-row gap-3">
                  <div className="d-flex flex-column flex-fill ">
                    <div className="form-check">
                      <input
                        className="form-check-input"
                        type="radio"
                        name="paymentMethod"
                        value="Cash On Delivery"
                        checked={formData.paymentMethod === "Cash On Delivery"}
                        onChange={handleChange}
                        id="cod"
                      />
                      <label className="form-check-label" htmlFor="cod">
                        Cash on Delivery
                      </label>
                    </div>
                  </div>
                  <div className="d-flex flex-column flex-fill me-5">
                    <div className="form-check">
                      <input
                        className="form-check-input"
                        type="radio"
                        name="paymentMethod"
                        value="Online Payment"
                        checked={formData.paymentMethod === "Online Payment"}
                        onChange={handleChange}
                        id="online"
                      />
                      <label className="form-check-label" htmlFor="online">
                        Online Payment
                      </label>
                    </div>
                  </div>
                </div>
              </div>
              {/* Card Details */}
              {formData.paymentMethod === "Online Payment" && (
                <>
                  <hr />
                  <h6 className="fw-bold mb-3">Card Details</h6>

                  {/* Card Number */}
                  <div className="mb-3">
                    <label className="form-label">Card Number</label>
                    <input
                      type="text"
                      name="cardNumber"
                      className="form-control"
                      placeholder="1234 5678 9012 3456"
                      value={formData.cardNumber}
                      onChange={(e) => {
                        let val = e.target.value.replace(/\D/g, "");
                        val = val.slice(0, 16); // allow up to 19 digits
                        val = val.replace(/(\d{4})(?=\d)/g, "$1 ");
                        setFormData((prev) => ({ ...prev, cardNumber: val }));
                      }}
                      inputMode="numeric"
                      maxLength="23" // spaces included
                      required
                    />
                  </div>

                  {/* Expiry + CVV */}
                  <div className="row">
                    <div className="col-6 mb-3">
                      <label className="form-label">Expiry</label>
                      <input
                        type="text"
                        name="expiry"
                        className="form-control"
                        placeholder="MM/YY"
                        value={formData.expiry}
                        onChange={(e) => {
                          let val = e.target.value
                            .replace(/[^0-9/]/g, "")
                            .slice(0, 5);
                          if (val.length === 2 && !val.includes("/")) {
                            val = val + "/";
                          }
                          setFormData((prev) => ({ ...prev, expiry: val }));
                        }}
                        required
                      />
                    </div>
                    <div className="col-6 mb-3">
                      <label className="form-label">CVV</label>
                      <input
                        type="password"
                        name="cvv"
                        className="form-control"
                        placeholder="***"
                        value={formData.cvv}
                        onChange={(e) => {
                          const onlyNums = e.target.value
                            .replace(/\D/g, "")
                            .slice(0, 4);
                          setFormData((prev) => ({ ...prev, cvv: onlyNums }));
                        }}
                        inputMode="numeric"
                        maxLength="4"
                        required
                      />
                    </div>
                  </div>
                </>
              )}

              <div className="d-grid mt-4">
                <button
                  type="submit"
                  className="btn7 fw-bold w-100"
                  style={{
                    height: "40px",
                    fontSize: "17px",
                    borderRadius: "5px",
                  }}
                  disabled={loading}
                >
                  {loading ? "Placing Order..." : "Order Now"}
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Check;

// src/app/pages/checkout.component.ts
import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { ApiService } from '../services/api.service';

declare global {
  interface Window {
    Razorpay: any;
  }
}

@Component({
  selector: 'app-checkout',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './checkout.component.html',
  styleUrls: ['./checkout.component.css']
})
export class CheckoutComponent implements OnInit {
  formData = {
    email: "",
    phone: "",
    countryCode: "+91",
    address: "",
    paymentMethod: "Cash On Delivery",
  };

  loading: boolean = false;
  errorMsg: string = "";

  constructor(
    private router: Router,
    private apiService: ApiService,
    private cdr: ChangeDetectorRef
  ) {}

  ngOnInit() {
    this.fetchUserProfile();
  }

  fetchUserProfile() {
    this.apiService.get<any>('api/order/profile').subscribe({
      next: (res) => {
        this.formData.email = res.email || "";
        this.formData.phone = res.phone || "";
        this.cdr.detectChanges();
      },
      error: (err) => {
        console.error("Error fetching profile", err);
        this.cdr.detectChanges();
      }
    });
  }

  loadRazorpayScript(): Promise<void> {
    return new Promise((resolve) => {
      if (window.Razorpay) {
        resolve();
        return;
      }
      const script = document.createElement('script');
      script.src = 'https://checkout.razorpay.com/v1/checkout.js';
      script.onload = () => resolve();
      script.onerror = () => resolve(); // still resolve so we can show error in placeOrder
      document.body.appendChild(script);
    });
  }

  placeOrder() {
    if (!this.formData.email?.trim() || !this.formData.phone?.trim() || !this.formData.address?.trim()) {
      this.errorMsg = "Please fill in all details and confirm your order.";
      return;
    }
    if (!this.formData.paymentMethod) {
      this.errorMsg = "Please select a payment method.";
      return;
    }

    this.errorMsg = "";

    if (this.formData.paymentMethod === "Cash On Delivery") {
      this.placeCodOrder();
      return;
    }

    if (this.formData.paymentMethod === "Online Payment") {
      this.openRazorpayCheckout();
      return;
    }

    this.errorMsg = "Invalid payment method.";
  }

  placeCodOrder() {
    this.loading = true;
    const payload = { ...this.formData };
    this.apiService.post("api/order/order", payload).subscribe({
      next: () => this.router.navigate(["/order-success"]),
      error: (err) => {
        console.error("Order failed", err);
        this.errorMsg = "❌ Order failed. Please try again.";
        this.loading = false;
      },
      complete: () => { this.loading = false; }
    });
  }

  openRazorpayCheckout() {
    this.loading = true;
    this.apiService.post<{ orderId: string; amount: number; currency: string; key_id: string }>(
      "api/order/create-razorpay-order",
      {}
    ).subscribe({
      next: (res) => {
        this.loadRazorpayScript().then(() => {
          if (!window.Razorpay) {
            this.errorMsg = "Payment script failed to load. Please try again.";
            this.loading = false;
            return;
          }
          const options = {
            key: res.key_id,
            amount: res.amount,
            currency: res.currency,
            order_id: res.orderId,
            name: "Starbucks",
            description: "Order payment",
            prefill: {
              email: this.formData.email,
              contact: this.formData.phone,
            },
            handler: (response: { razorpay_order_id: string; razorpay_payment_id: string; razorpay_signature: string }) => {
              this.verifyAndPlaceOrder(response);
            },
            modal: {
              ondismiss: () => {
                this.loading = false;
                alert("Payment cancelled. Please make payment to complete your order.");
              },
            },
          };
          const rzp = new window.Razorpay(options);
          rzp.open();
        });
      },
      error: (err) => {
        console.error("Create Razorpay order failed", err);
        this.errorMsg = err.error?.message || "❌ Could not start payment. Please try again.";
        this.loading = false;
      },
    });
  }

  verifyAndPlaceOrder(razorpayResponse: { razorpay_order_id: string; razorpay_payment_id: string; razorpay_signature: string }) {
    const payload = {
      razorpay_order_id: razorpayResponse.razorpay_order_id,
      razorpay_payment_id: razorpayResponse.razorpay_payment_id,
      razorpay_signature: razorpayResponse.razorpay_signature,
      email: this.formData.email,
      phone: this.formData.phone,
      countryCode: this.formData.countryCode,
      address: this.formData.address,
    };
    this.apiService.post("api/order/verify-payment", payload).subscribe({
      next: () => this.router.navigate(["/order-success"]),
      error: (err) => {
        console.error("Verify payment failed", err);
        this.errorMsg = err.error?.message || "❌ Payment verification failed. Please contact support if amount was deducted.";
        this.loading = false;
      },
      complete: () => { this.loading = false; }
    });
  }
}

<div class="container py-4">
  <div class="row justify-content-center">
    <div class="col-lg-7 col-md-8">
      <div class="card shadow-lg border-0 p-4 rounded-4">
        <h1 class="fs-3 text-success text-center fw-bold checkout-title">
          Payment
        </h1>
        <p class="text-success fw-bold text-center checkout-subtitle">
          Brew & Pay • Easy Checkout
        </p>
        <hr />
        <div *ngIf="errorMsg" class="alert alert-danger py-2">{{ errorMsg }}</div>

        <form (ngSubmit)="placeOrder()" #checkoutForm="ngForm">
          <!-- Email + Phone -->
          <div class="mb-3 d-flex flex-column flex-sm-row gap-3">
            <div class="d-flex flex-column flex-fill">
              <label class="form-label fw-semibold">Email ID</label>
              <input
                type="email"
                name="email"
                class="form-control form-control-lg rounded-3"
                [(ngModel)]="formData.email"
                readonly
                [value]="formData.email"
                required
              />
            </div>
            <div class="d-flex flex-column flex-fill">
              <label class="form-label fw-semibold">Phone Number</label>
              <div class="input-group">
                <select
                  class="form-select"
                  [(ngModel)]="formData.countryCode"
                  name="countryCode"
                  style="max-width: 100px; height: 50px"
                  disabled
                >
                  <option value="+91">+91 🇮🇳</option>
                </select>
                <input
                  type="tel"
                  name="phone"
                  class="form-control phono"
                  [(ngModel)]="formData.phone"
                  readonly
                  [value]="formData.phone"
                  pattern="[0-9]{10}"
                  required
                />
              </div>
            </div>
          </div>

          <!-- Address -->
          <div class="mb-3">
            <label class="form-label fw-semibold">
              Shipping Address
            </label>
            <textarea
              name="address"
              class="form-control rounded-3"
              placeholder="Enter your address"
              style="resize: none; height: 100px"
              [(ngModel)]="formData.address"
              required
            ></textarea>
          </div>

           <!-- Payment Method -->
          <div class="mb-3">
            <label class="form-label fw-semibold">Payment Method</label>
            <div class="mb-3 d-flex flex-column flex-sm-row gap-3">
              <div class="d-flex flex-column flex-fill ">
                <div class="form-check">
                  <input
                    class="form-check-input"
                    type="radio"
                    name="paymentMethod"
                    value="Cash On Delivery"
                    [(ngModel)]="formData.paymentMethod"
                    id="cod"
                  />
                  <label class="form-check-label" for="cod">
                    Cash on Delivery
                  </label>
                </div>
              </div>
              <div class="d-flex flex-column flex-fill me-5">
                <div class="form-check">
                  <input
                    class="form-check-input"
                    type="radio"
                    name="paymentMethod"
                    value="Online Payment"
                    [(ngModel)]="formData.paymentMethod"
                    id="online"
                  />
                  <label class="form-check-label" for="online">
                    Online Payment
                  </label>
                </div>
              </div>
            </div>
          </div>
          <!-- Online Payment: Razorpay info -->
          <div *ngIf="formData.paymentMethod === 'Online Payment'" class="mb-3">
            <p class="text-muted small mb-0">
              <i class="fas fa-lock me-1"></i> You will be redirected to Razorpay for secure payment (card, UPI, netbanking).
            </p>
          </div>

          <div class="d-grid mt-4">
            <!-- Cash on Delivery: show Order Now button -->
            <button
              *ngIf="formData.paymentMethod === 'Cash On Delivery'"
              type="submit"
              class="btn7 fw-bold w-100"
              style="height: 40px; font-size: 17px; border-radius: 5px;"
            >
              {{ loading ? "Placing Order..." : "Order Now" }}
            </button>
            <!-- Online Payment: show Proceed to Payment button -->
            <button
              *ngIf="formData.paymentMethod === 'Online Payment'"
              type="submit"
              class="btn7 fw-bold w-100"
              style="height: 40px; font-size: 17px; border-radius: 5px;"
            >
              {{ loading ? "Processing..." : "Proceed to Payment" }}
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
