// src/Item.jsx
import React, { useEffect, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import "bootstrap/dist/css/bootstrap.min.css";
import "./css/Home.css"; // 🔹 popup CSS અહીં હશે
import axios from "axios";

// 🔹 Static Product List
const products1 = [
  { id: 0, image: "https://starbucksstatic.cognizantorderserv.com/Items/Small/100501.jpg", title: "Java Chip Frappuccino", per:"Mocha sauce and Frappuccino® chips blended with with Frappu..",price: 441 },
  { id: 1, image: "https://starbucksstatic.cognizantorderserv.com/Items/Small/112539.jpg", title: "Picco Cappuccino", per:"Dark, Rich in flavour espresso lies in wait under a smoothed..",price: 200 },
  { id: 2, image: "https://starbucksstatic.cognizantorderserv.com/Items/Small/100385.jpg", title: "Iced Caffe Latte",per:"Our dark, Rich in flavour espresso is combined with milk and..", price: 372 },

];

const Item = () => {
  const [filteredProducts, setFilteredProducts] = useState(products1);
  const navigate = useNavigate();
  const [loading, setLoading] = useState(false);
  const location = useLocation();
  const token = localStorage.getItem("token");

  const [showToast, setShowToast] = useState(false);
  const [toastMessage, setToastMessage] = useState("");

  // 🔹 Search Filter
  useEffect(() => {
    const query = new URLSearchParams(location.search).get("q")?.toLowerCase() || "";
    if (query) {
      setLoading(true);
      setTimeout(() => {
        const filtered = products1.filter((item) =>
          item.title.toLowerCase().includes(query)
        );
        setFilteredProducts(filtered);
        setLoading(false);
      }, 1000);
    } else {
      setFilteredProducts(products1);
    }
  }, [location.search]);

  // 🔹 Add to Cart Function + Popup Message
  const addToCart = async (product) => {
    if (!token) {
      alert("Please login to add items to cart.");
      navigate("/login");
      return;
    }

    try {
      await axios.post(
        "https://backend-t19q.onrender.com/add-to-cart",
        {
          productId: product.id,
          image: product.image,
          title: product.title,
          price: product.price,
        },
        { headers: { Authorization: `Bearer ${token}` } }
      );

      // ✅ Show Popup Message
      setToastMessage(`${product.title} added to cart!`);
      setShowToast(true);
      setTimeout(() => setShowToast(false), 3000);

    } catch (err) {
      console.error(err);
      alert("Failed to add item");
    }
  };

  return (
    <>
      {/* 🔹 Popup Top Center */}
      {showToast && (
        <div className="toast-popup bg-success">
          🛒 {toastMessage}
        </div>
      )}

      <div className="container mt-4">
        {loading ? (
          <div className="alert alert-info text-center mt-3 mb-2">🔄 Searching...</div>
        ) : filteredProducts.length === 0 ? (
          <div className="alert alert-warning text-center">
            ❌ No products found.
          </div>
        ) : (
          <div className="container" id="products1">
            {filteredProducts.map((item) => (
              <div key={item.id} className="box">
                <div className="img-box1">
                  <img className="images1" src={item.image} alt={item.title} />
                </div>
                  <div className="bottom">
                    <h2>{item.title}</h2>
                    <h4>{item.per}</h4>
                    <h3>  ₹{item.price}.00</h3>
                    <button className="btn4" onClick={() => addToCart(item)}>
                      Add Item
                    </button>
                  </div>
                </div>  
            ))}
          </div>
        )}
      </div>
    </>
  );
};

export default Item;

// src/app/pages/item.component.ts
import { Component, OnInit, OnDestroy, PLATFORM_ID, inject, ChangeDetectorRef } from '@angular/core';
import { CommonModule, isPlatformBrowser } from '@angular/common';
import { ActivatedRoute, Router } from '@angular/router';
import { ApiService } from '../services/api.service';
import { Product } from '../models/product.model';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-item',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './item.component.html',
  styleUrls: ['./item.component.css']
})
export class ItemComponent implements OnInit, OnDestroy {
  products1: Product[] = [
    {
      id: 0,
      image: "https://starbucksstatic.cognizantorderserv.com/Items/Small/100501.jpg",
      title: "Java Chip Frappuccino",
      per: "Mocha sauce and Frappuccino® chips blended with with Frappu..",
      price: 441,
    },
    {
      id: 1,
      image: "https://starbucksstatic.cognizantorderserv.com/Items/Small/112539.jpg",
      title: "Picco Cappuccino",
      per: "Dark, Rich in flavour espresso lies in wait under a smoothed..",
      price: 200,
    },
    {
      id: 2,
      image: "https://starbucksstatic.cognizantorderserv.com/Items/Small/100385.jpg",
      title: "Iced Caffe Latte",
      per: "Our dark, Rich in flavour espresso is combined with milk and..",
      price: 372,
    },
  ];

  filteredProducts: Product[] = [];
  loading: boolean = false;
  private queryParamsSubscription?: Subscription;
  private platformId = inject(PLATFORM_ID);

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private apiService: ApiService,
    private cdr: ChangeDetectorRef
  ) {}

  ngOnInit() {
    // Initialize filtered products immediately
    this.filteredProducts = [...this.products1];
    
    // Subscribe to query params without delay
    this.queryParamsSubscription = this.route.queryParams.subscribe(params => {
      const query = params['q']?.toLowerCase() || "";
      this.applyFilter(query);
    });
  }

  ngOnDestroy() {
    if (this.queryParamsSubscription) {
      this.queryParamsSubscription.unsubscribe();
    }
  }

  applyFilter(query: string = "") {
    if (!query) {
      this.filteredProducts = [...this.products1];
      return;
    }
    
    this.filteredProducts = this.products1.filter(item =>
      (item.title || "").toLowerCase().includes(query)
    );
    this.cdr.detectChanges();
  }

  addToCart(product: Product) {
    const token = isPlatformBrowser(this.platformId) ? localStorage.getItem("token") : null;
    if (!token) {
      alert("Please login to add items to cart.");
      this.router.navigate(["/login"]);
      return;
    }

    this.apiService.post("api/cart/add-to-cart", {
      productId: product.id?.toString() || "",
      image: product.image,
      title: product.title || "",
      price: product.price || 0,
    }).subscribe({
      next: () => {
        alert("Item added to cart successfully");
      },
      error: (error) => {
        console.error(error);
        alert("Already added item");
      }
    });
  }
}

<div class="Herosection_1">
  <div class="container">
    <div *ngIf="loading" class="d-flex justify-content-center align-items-center my-5">
      <div class="spinner-border text-success mb-4" role="status">
        <span class="visually-hidden">Loading...</span>
      </div>
    </div>

    <ng-container *ngIf="!loading">
      <div *ngIf="filteredProducts.length === 0"
           class="alert alert-danger text-center mt-3 fw-bold mb-4 m-auto"
           style="width: 18%; background-color: #e7414c; color: white;">
        No products found.
      </div>

      <div *ngIf="filteredProducts.length > 0" class="container" id="products1">
        <div *ngFor="let item of filteredProducts" class="box1">
          <div class="img-box1">
            <img class="images1" [src]="item.image" [alt]="item.title" />
          </div>

          <div class="bottom">
            <h2>{{item.title}}</h2>
            <h4>{{item.per}}</h4>
            <h3>₹{{item.price}}.00</h3>

            <button class="btn4" (click)="addToCart(item)">
              Add Item
            </button>
          </div>
        </div>
      </div>
    </ng-container>
  </div>
</div>
