// src/Login.jsx
import React, { useState } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import RedirectLoader from "./RedirectLoader";
import "./css/Login.css";
import "bootstrap/dist/css/bootstrap.min.css";

const Login = ({ setUsername }) => {
  const [emailInput, setEmailInput] = useState("");
  const [password, setPassword] = useState("");
  const [strengthMessage, setStrengthMessage] = useState("");
  const [errorMessage, setErrorMessage] = useState("");
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();

  const handlePasswordChange = (e) => {
    const value = e.target.value;
    setPassword(value);

    if (value.length < 4) {
      setStrengthMessage("Weak password ❌");
    } else if (/[A-Z]/.test(value) && /\d/.test(value) && value.length >= 8) {
      setStrengthMessage("Strong password ✅");
    } else {
      setStrengthMessage("Moderate password ⚠️");
    }
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    setLoading(true);

    axios
      .post("https://backend-t19q.onrender.com/login", {
        email: emailInput.toLowerCase(),
        password,
      })
      .then((res) => {
        if (res.data.message === "Success") {
          localStorage.setItem("token", res.data.token);
          localStorage.setItem("username", res.data.username);
          setUsername(res.data.username);
          // notify server already emits user:status on login; nothing to do client-side
        } else {
          setErrorMessage(res.data.message);
          setLoading(false);
        }
      })
      .catch((err) => {
        console.error(err);
        setErrorMessage("Server error. Try again later.");
        setLoading(false);
      });
  };

  if (loading) {
    return <RedirectLoader seconds={3} onComplete={() => navigate("/")} />;
  }

  return (
    <div className="body">
      <div className="container d-flex justify-content-center align-items-center vh-100">
        <div className="login-container">
          <h2 className="text-success text-center mb-3  h2 ">Login</h2>
          <hr />
          {errorMessage && (
            <div className="alert alert-danger">{errorMessage}</div>
          )}
          <form onSubmit={handleSubmit} autoComplete="off">
            <div className="mb-3">
              <label className="form-label">Email</label>
              <input
                type="email"
                name="email"
                className="form-control"
                placeholder="example@gmail.com"
                value={emailInput}
                onChange={(e) => setEmailInput(e.target.value)}
                autoComplete="off"
                inputMode="email"
                autoCapitalize="none"
                autoCorrect="off"
                spellCheck={false}
                data-form-type="other"
                aria-autocomplete="none"
                required
              />
            </div>

            <div className="mb-3">
              <label className="form-label">Password</label>
              <input
                type="password"
                name="password"
                className="form-control"
                placeholder="*********"
                value={password}
                onChange={handlePasswordChange}
                autoComplete="off"
                autoCapitalize="none"
                autoCorrect="off"
                spellCheck={false}
                data-form-type="other"
                aria-autocomplete="none"
                required
              />
              <small className="text-muted strength">{strengthMessage}</small>
            </div>

            <p className="mt-1 fw-bold">
              <a
                href="/changepassword"
                className="text-decoration-none text-success "
              >
                Change Password
              </a>
            </p>

            <button type="submit" className="btn7 fw-bold w-100 rounded">
              Login
            </button>
          </form>

          <p className="mt-3 text-center">
            Don't have an account?{" "}
            <a
              href="/register"
              className="text-decoration-none fw-bold text-success"
            >
              Register
            </a>
          </p>
        </div>
      </div>
    </div>
  );
};

export default Login;

// src/app/pages/login.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router, RouterModule } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { AuthService } from '../services/auth.service';
import { ApiService } from '../services/api.service';
import { RedirectLoaderComponent } from '../components/redirect-loader.component';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule, RedirectLoaderComponent],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  emailInput: string = '';
  password: string = '';
  strengthMessage: string = '';
  errorMessage: string = '';
  loading: boolean = false;

  constructor(
    private authService: AuthService,
    private router: Router,
    private apiService: ApiService
  ) {}

  handlePasswordChange() {
    const value = this.password;
    if (value.length < 4) {
      this.strengthMessage = "Weak password ❌";
    } else if (/[A-Z]/.test(value) && /\d/.test(value) && value.length >= 8) {
      this.strengthMessage = "Strong password ✅";
    } else {
      this.strengthMessage = "Moderate password ⚠️";
    }
  }

  handleSubmit() {
    // Validate input before submitting
    if (!this.emailInput || !this.emailInput.trim()) {
      this.errorMessage = "Email is required";
      return;
    }

    if (!this.password || !this.password.trim()) {
      this.errorMessage = "Password is required";
      return;
    }

    // Basic email format validation
    const emailPattern = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailPattern.test(this.emailInput)) {
      this.errorMessage = "Please enter a valid email address";
      return;
    }

    this.loading = true;
    this.errorMessage = "";

    this.apiService.post<any>("api/user/login", {
      email: this.emailInput.toLowerCase().trim(),
      password: this.password,
    }).subscribe({
      next: (res) => {
        // Only proceed if response has Success message AND token
        if (res && res.message === "Success" && res.token && res.username) {
          this.authService.setToken(res.token);
          this.authService.setUsername(res.username);
          // Redirection is handled by the loading state and RedirectLoader
        } else {
          // If no token or success message, show error
          this.errorMessage = res?.message || "Login failed. Please check your credentials.";
          this.loading = false;
        }
      },
      error: (err) => {
        console.error("Login error:", err);
        console.error("Error status:", err.status);
        console.error("Error message:", err.error);
        
        // Handle different error status codes
        if (err.status === 404) {
          this.errorMessage = err.error?.message || "User not found. Please register first.";
        } else if (err.status === 401 || err.status === 403) {
          this.errorMessage = err.error?.message || "Invalid email or password. Please check your credentials.";
        } else if (err.status === 400) {
          this.errorMessage = err.error?.message || "Invalid input. Please check your email and password.";
        } else if (err.status === 0 || err.status === undefined) {
          this.errorMessage = "Unable to connect to server. Please try again later.";
        } else {
          this.errorMessage = err.error?.message || "Server error. Please try again later.";
        }
        this.loading = false;
      }
    });
  }
}

<div class="body">
  <ng-container *ngIf="loading; else loginForm">
    <app-redirect-loader [seconds]="3" [redirectUrl]="'/'"></app-redirect-loader>
  </ng-container>

  <ng-template #loginForm>
    <div class="container d-flex justify-content-center align-items-center vh-100">
      <div class="login-container">
        <h2 class="text-success text-center mb-3 h2">Login</h2>
        <hr />
        <div *ngIf="errorMessage" class="alert alert-danger">{{errorMessage}}</div>
        <form (submit)="handleSubmit()" autocomplete="off">
          <div class="mb-3">
            <label class="form-label">Email</label>
            <input
              type="email"
              name="email"
              class="form-control"
              placeholder="example@gmail.com"
              [(ngModel)]="emailInput"
              autocomplete="off"
              inputmode="email"
              autocapitalize="none"
              autocorrect="off"
              [spellcheck]="false"
              required
            />
          </div>

          <div class="mb-3">
            <label class="form-label">Password</label>
            <input
              type="password"
              name="password"
              class="form-control"
              placeholder="*********"
              [(ngModel)]="password"
              (ngModelChange)="handlePasswordChange()"
              autocomplete="off"
              autocapitalize="none"
              autocorrect="off"
              [spellcheck]="false"
              required
            />
            <small class="text-muted strength">{{strengthMessage}}</small>
          </div>

          <button type="submit" class="btn7 fw-bold w-100 rounded">
            Login
          </button>
        </form>

        <p class="mt-3 text-center">
          Don't have an account? 
          <a
            routerLink="/register"
            class="text-decoration-none fw-bold text-success"
          >
            Register
          </a>
        </p>
      </div>
    </div>
  </ng-template>
</div>
