// src/Menu.jsx
import React, { useEffect, useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import "bootstrap/dist/css/bootstrap.min.css";
import "./css/Menu.css";
import axios from "axios";

const Item = () => {
  const navigate = useNavigate();
  const [products, setProducts] = useState([]);
  const [filteredProducts, setFilteredProducts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const location = useLocation();
  const token = localStorage.getItem("token");

  const [showToast, setShowToast] = useState(false);
  const [toastMessage, setToastMessage] = useState("");

  // 🔹 Fetch products with proper loading state management
  useEffect(() => {
    const fetchProducts = async () => {
      try {
        // Always set loading to true initially to prevent flash
        setLoading(true);

        const response = await axios.get(
          "https://backend-t19q.onrender.com/api/products?displayOnMenu=true"
        );

        // Set products immediately
        setProducts(response.data);
        setFilteredProducts(response.data);
        setError(null);

        // Check if this is first load for spinner timing
        const isFirstLoad = !sessionStorage.getItem("menuPageLoaded");

        if (isFirstLoad) {
          // First load → show spinner for 2.5 seconds
          setTimeout(() => {
            setLoading(false);
            sessionStorage.setItem("menuPageLoaded", "true");
          }, 700);
        } else {
          // Subsequent loads → show data immediately
          setLoading(false);
        }
      } catch (err) {
        console.error("Error fetching products:", err);
        setError("Failed to load products");
        setProducts([]);
        setFilteredProducts([]);
        setLoading(false);
      }
    };

    fetchProducts();
  }, []);

  // Handle search filtering
  useEffect(() => {
    const query =
      new URLSearchParams(location.search).get("q")?.toLowerCase() || "";
    if (query) {
      setLoading(true);
      setTimeout(() => {
        const filtered = products.filter((item) =>
          item.name.toLowerCase().includes(query)
        );
        setFilteredProducts(filtered);
        setLoading(false);
      }, 1000);
    } else {
      setFilteredProducts(products);
    }
  }, [location.search, products]);

  const addToCart = async (product) => {
    if (!token) {
      alert("Please login to add items to cart.");
      navigate("/login");
      return;
    }
    try {
      await axios.post(
        "https://backend-t19q.onrender.com/add-to-cart",
        {
          productId: product._id,
          image: product.image,
          title: product.name,
          price: product.price,
        },
        {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        }
      );

      setToastMessage(`${product.name} added to cart!`);
      setShowToast(true);
      setTimeout(() => setShowToast(false), 3000);
    } catch (error) {
      console.error(error);
      alert("Error adding item");
    }
  };

  if (loading && products.length === 0) {
    return (
      <div className="Herosection_1">
        <div className="container">
          <div
            className="d-flex justify-content-center align-items-center"
            style={{ height: "200px", width: "100%" }}
          >
            <div className="spinner-border text-success" role="status">
              <span className="visually-hidden">Loading...</span>
            </div>
          </div>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="Herosection_1">
        <div className="container">
          <div className="alert alert-danger text-center">❌ {error}</div>
        </div>
      </div>
    );
  }

  return (
    <>
      {showToast && (
        <div className="toast-popup bg-success">🛒 {toastMessage}</div>
      )}
      <div className="Herosection_1">
        <div className="container">
          {loading ? (
            <div className="d-flex justify-content-center align-items-center my-4">
              <div className="spinner-border text-success" role="status">
                <span className="visually-hidden">Loading...</span>
              </div>
            </div>
          ) : filteredProducts.length === 0 ? (
            <div
              className="alert alert-danger text-center mt-3 fw-bold align-items-center"
              style={{
                width: "18%",
                backgroundColor: "#e7414c",
                margin: "20px auto", // centers horizontally
              }}
            >
              {products.length === 0
                ? "❌ No products found."
                : " No found products."}
            </div>
          ) : (
            <div id="products3">
              {filteredProducts.map((item) => (
                <div key={item._id} className="box2">
                  <div className="img-box1">
                    <img className="images1" src={item.image} alt={item.name} />
                  </div>
                  <div className="bottom">
                    <h2>{item.name}</h2>
                    <h4>{item.description}</h4>
                    <h3>₹{item.price}.00</h3>
                    <button className="btn4" onClick={() => addToCart(item)}>
                      Add Item
                    </button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Enhanced Modern Footer */}
      <footer className="bg-dark text-white pt-5 pb-3 fw-medium shadow-lg mt-3">
        <div className="container">
          <div className="row justify-content-start">
            {/* Contact Info Left Aligned */}
            <div className="col-md-5 mb-4 text-md-start text-center">
              <h5 className="text-uppercase fw-bold text-warning mb-3 border-bottom border-warning pb-2">
                Contact
              </h5>
              <p className="mb-2">
                <i className="fas fa-map-marker-alt me-2 text-warning"></i>
                Surat, Gujarat
              </p>
              <p className="mb-2">
                <i className="far fa-envelope me-2 text-warning"></i>
                vaghelaparth2005@gmail.com
              </p>
              <p>
                <i className="fas fa-phone me-2 text-warning"></i>
                +91 8735035021
              </p>
            </div>
          </div>

          <hr className=" border-secondary" />

          <div className="row align-items-center justify-content-between">
            <div className="col-md-6 text-md-start text-center  mb-md-0">
              <p className="mb-0">
                Owned by:{" "}
                <strong className="text-warning text-decoration-none">
                  Noob Ninjas
                </strong>
              </p>
            </div>

            {/* Social Icons Modernized */}
            <div className="col-md-6 text-md-end text-center">
              <ul className="list-inline mb-0">
                {[
                  { icon: "facebook-f", link: "#" },
                  { icon: "x-twitter", link: "#" },
                  { icon: "linkedin-in", link: "#" },
                  { icon: "instagram", link: "#" },
                  { icon: "youtube", link: "#" },
                ].map((social, idx) => (
                  <li className="list-inline-item mx-1" key={idx}>
                    <a
                      href={social.link}
                      className="social-icon d-inline-flex align-items-center justify-content-center rounded-circle"
                      aria-label={social.icon}
                    >
                      <i className={`fab fa-${social.icon}`}></i>
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      </footer>
    </>
  );
};

export default Item;

// src/app/pages/menu.component.ts
import { Component, OnInit, OnDestroy, PLATFORM_ID, inject, ChangeDetectorRef } from '@angular/core';
import { CommonModule, isPlatformBrowser } from '@angular/common';
import { ActivatedRoute, Router, RouterModule } from '@angular/router';
import { ApiService } from '../services/api.service';
import { Product } from '../models/product.model';
import { Subscription } from 'rxjs';

@Component({
  selector: 'app-menu',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './menu.component.html',
  styleUrls: ['./menu.component.css']
})
export class MenuComponent implements OnInit, OnDestroy {
  products: Product[] = [];
  filteredProducts: Product[] = [];
  loading: boolean = false;
  error: string | null = null;
  private queryParamsSubscription?: Subscription;

  socials = [
    { icon: "facebook-f", link: "#" },
    { icon: "x-twitter", link: "#" },
    { icon: "linkedin-in", link: "#" },
    { icon: "instagram", link: "#" },
    { icon: "youtube", link: "#" },
  ];

  private platformId = inject(PLATFORM_ID);

  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private apiService: ApiService,
    private cdr: ChangeDetectorRef
  ) {}

  ngOnInit() {
    // Reset state when component initializes
    this.loading = true;
    this.error = null;
    this.products = [];
    this.filteredProducts = [];
    
    // Fetch products immediately - ensure it happens
    this.fetchProducts();
    
    // Subscribe to query params after initial load
    this.queryParamsSubscription = this.route.queryParams.subscribe(params => {
      const query = params['q']?.toLowerCase() || "";
      if (this.products.length > 0) {
        this.applyFilter(query);
      }
    });
  }

  ngOnDestroy() {
    if (this.queryParamsSubscription) {
      this.queryParamsSubscription.unsubscribe();
    }
  }

  applyFilter(query: string = "") {
    if (!query) {
      this.filteredProducts = [...this.products];
      return;
    }
    
    if (this.products.length === 0) {
      return;
    }
    
    this.filteredProducts = this.products.filter(item =>
      (item.name || "").toLowerCase().includes(query)
    );
  }

  fetchProducts() {
    this.loading = true;
    this.error = null;
    
    // Ensure we're making the request
    const request = this.apiService.get<Product[]>("api/products/products/public?displayOnMenu=true");
    
    request.subscribe({
      next: (data) => {
        this.products = data || [];
        this.error = null;

        // Apply filter if query params exist
        const currentQuery = this.route.snapshot.queryParams['q']?.toLowerCase() || "";
        this.applyFilter(currentQuery);

        this.loading = false;
        this.cdr.detectChanges();
      },
      error: (err) => {
        console.error("Error fetching products:", err);
        this.error = "Failed to load products";
        this.loading = false;
        this.products = [];
        this.filteredProducts = [];
        this.cdr.detectChanges();
      }
    });
  }

  addToCart(product: Product) {
    const token = isPlatformBrowser(this.platformId) ? localStorage.getItem("token") : null;
    if (!token) {
      alert("Please login to add items to cart.");
      this.router.navigate(["/login"]);
      return;
    }

    this.apiService.post("api/cart/add-to-cart", {
      productId: product._id,
      image: product.image,
      title: product.name,
      price: product.price,
    }).subscribe({
      next: () => {
        alert("Item added to cart successfully");
      },
      error: (error) => {
        console.error(error);
        alert("Already added item");
      }
    });
  }
}

<div class="Herosection_1">
  <div class="container">
    <div *ngIf="loading && products.length === 0"
         class="d-flex justify-content-center align-items-center"
         style="height: 200px; width: 100%;">
      <div class="spinner-border text-success" role="status">
        <span class="visually-hidden">Loading...</span>
      </div>
    </div>

    <div *ngIf="error" class="alert alert-danger text-center">❌ {{error}}</div>

    <ng-container *ngIf="!error && !(loading && products.length === 0)">
      <div *ngIf="loading" class="d-flex justify-content-center align-items-center my-4">
        <div class="spinner-border text-success" role="status">
          <span class="visually-hidden">Loading...</span>
        </div>
      </div>

      <ng-container *ngIf="!loading">
        <div *ngIf="filteredProducts.length === 0"
             class="alert alert-danger text-center mt-3 fw-bold align-items-center"
             style="width: 18%; background-color: #e7414c; margin: 20px auto; color: white;">
          {{products.length === 0 ? "❌ No products found." : " No found products."}}
        </div>

        <div *ngIf="filteredProducts.length > 0" id="products3">
          <div *ngFor="let item of filteredProducts" class="box2">
            <div class="img-box1">
              <img class="images1" [src]="item.image" [alt]="item.name" />
            </div>
            <div class="bottom">
              <h2>{{item.name}}</h2>
              <h4>{{item.description}}</h4>
              <h3>₹{{item.price}}.00</h3>
              <button class="btn4" (click)="addToCart(item)">
                Add Item
              </button>
            </div>
          </div>
        </div>
      </ng-container>
    </ng-container>
  </div>
</div>
<!-- Enhanced Modern Footer -->
<footer class="text-white pt-5 pb-3 fw-medium shadow-lg footer">
  <div class="container">
    <div class="row justify-content-start">
      <div class="col-md-5 mb-4 text-md-start text-center">
        <h5 class="text-uppercase fw-bold text-white mb-3 border-white h5 pb-2 hedding-font">
          Contact
        </h5>
        <p class="mb-2">
          <i class="fas fa-map-marker-alt me-2 text-white"></i>
          Surat, Gujarat
        </p>
        <p class="mb-2">
          <i class="far fa-envelope me-2 text-white"></i>
          vaghelaparth2005@gmail.com
        </p>
        <p>
          <i class="fas fa-phone me-2 text-white"></i>
          +91 8735035021
        </p>
      </div>
    </div>

    <hr class="border-secondary" />

    <div class="row align-items-center justify-content-between">
      <div class="col-md-6 text-md-start text-center mb-md-0 hedding-font fw-bold">
        <p class="mb-0">
          Owned by:
          <strong class="text-white text-decoration-none">
          Noob Ninjas
          </strong>
        </p>
      </div>

      <div class="col-md-6 text-md-end text-center">
        <ul class="list-inline mb-0">
          <li *ngFor="let social of socials" class="list-inline-item mx-1">
            <a
              [href]="social.link"
              class="social-icon d-inline-flex align-items-center justify-content-center rounded-circle"
              [attr.aria-label]="social.icon"
            >
              <i [class]="'fab fa-' + social.icon"></i>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>
