// src/admin/Users.jsx
import { useState, useEffect } from "react";
import {
  Search,
  Trash2,
  Mail,
  Phone,
  Calendar,
  User,
  Users as UsersIcon,
  Cake,
  Activity,
  Filter,
} from "lucide-react";
import axios from "axios";
import "./Users.css";

const StatBreakdown = ({ list }) => {
  const now = new Date();
  const weekAgo = new Date();
  weekAgo.setDate(weekAgo.getDate() - 7);

  const thisWeek = list.filter((u) => new Date(u.createdAt) >= weekAgo).length;
  const thisMonth = list.filter((u) => {
    const date = new Date(u.createdAt);
    return (
      date.getMonth() === now.getMonth() &&
      date.getFullYear() === now.getFullYear()
    );
  }).length;

  return (
    <div style={{ fontSize: "0.8rem", color: "#374151", marginTop: "4px" }}>
      <div>This Week: {thisWeek}</div>
      <div>This Month: {thisMonth}</div>
    </div>
  );
};

const Users = () => {
  const [users, setUsers] = useState([]);
  const [filteredUsers, setFilteredUsers] = useState([]);
  const [searchTerm, setSearchTerm] = useState("");
  const [statusFilter, setStatusFilter] = useState("all");
  const [loading, setLoading] = useState(true);
  const [totalUsers, setTotalUsers] = useState(0);
  const [error, setError] = useState(null);

  useEffect(() => {
    const fetchUsers = async () => {
      try {
        const token = localStorage.getItem("adminToken");
        if (!token) {
          setError("Admin token missing. Please login.");
          setLoading(false);
          return;
        }

        const response = await axios.get("https://backend-t19q.onrender.com/admin/users", {
          headers: { Authorization: `Bearer ${token}` },
        });

        setUsers(response.data);
        setFilteredUsers(response.data);
        setTotalUsers(response.data.length);
      } catch (err) {
        console.error("Error fetching users:", err);
        setError("Failed to fetch users. Check connection.");
      } finally {
        setLoading(false);
      }
    };

    fetchUsers();
  }, []);

  useEffect(() => {
    let filtered = users;

    if (searchTerm) {
      filtered = filtered.filter(
        (user) =>
          (user.username?.toLowerCase() || "").includes(
            searchTerm.toLowerCase()
          ) ||
          (user.email?.toLowerCase() || "").includes(
            searchTerm.toLowerCase()
          ) ||
          (user.phone?.toLowerCase() || "").includes(searchTerm.toLowerCase())
      );
    }

    if (statusFilter !== "all") {
      filtered = filtered.filter(
        (user) => (user.status || "active").toLowerCase() === statusFilter
      );
    }

    setFilteredUsers(filtered);
  }, [users, searchTerm, statusFilter]);


  const formatDate = (dateStr) =>
    dateStr ? new Date(dateStr).toLocaleDateString() : "N/A";

  const calculateAge = (dob) => {
    if (!dob) return 0;
    const today = new Date();
    const birthDate = new Date(dob);
    let age = today.getFullYear() - birthDate.getFullYear();
    const m = today.getMonth() - birthDate.getMonth();
    if (m < 0 || (m === 0 && today.getDate() < birthDate.getDate())) age--;
    return age;
  };

 

  const getGenderBadge = (gender) => {
    const genderClasses = {
      male: "status-badge status-male",
      female: "status-badge status-female",
      other: "status-badge status-other",
    };
    return genderClasses[gender?.toLowerCase()] || "status-badge";
  };

  if (loading) {
    return (
      <div className="loading">
        <Activity className="animate-spin" />
        <span>Loading users...</span>
      </div>
    );
  }

  if (error) {
    return (
      <div className="error-message">
        <p>{error}</p>
      </div>
    );
  }

  return (
    <div className="container">
      <div className="users-container">
        <div className="page-header">
          <h1>Users Management</h1>
          <p>Manage all registered users</p>
        </div>
        <hr />

        {/* Stats Cards */}
        <div className="stats-grid">
          <div className="stat-card">
            <div className="stat-header">
              <span>Total Users</span>
              <div className="stat-icon bg-blue">
                <UsersIcon size={20} />
              </div>
            </div>
            <div className="stat-value">{totalUsers}</div>
          </div>

          <div className="stat-card">
            <div className="stat-header">
              <span>Active Users</span>
              <div className="stat-icon bg-green">
                <User size={20} />
              </div>
            </div>
            <div className="stat-value">
              {
                users.filter(
                  (u) => (u.status || "active").toLowerCase() === "active"
                ).length
              }
            </div>
          </div>

          <div className="stat-card">
            <div className="stat-header">
              <span>New This Month</span>
              <div className="stat-icon bg-yellow">
                <Calendar size={20} />
              </div>
            </div>
            <div className="stat-value">
              {
                users.filter((u) => {
                  const d = new Date(u.createdAt);
                  const now = new Date();
                  return (
                    d.getMonth() === now.getMonth() &&
                    d.getFullYear() === now.getFullYear()
                  );
                }).length
              }
            </div>
          </div>

          <div className="stat-card">
            <div className="stat-header">
              <span className="stat-title fw-bold">Registration Trend</span>
              <div className="stat-icon" style={{ backgroundColor: "#6b7280" }}>
                <Calendar size={16} />
              </div>
            </div>
            <div className="state">
              <StatBreakdown list={users} />
            </div>
          </div>
        </div>

        {/* Search & Filter */}
        <div className="search-filter-container">
          <div className="search-input position-relative flex-grow-1">
            <Search
              size={18}
              className="search-icon position-absolute"
              style={{ top: "50%", left: "15px", transform: "translateY(-50%)" }}
            />
            <input
              type="text"
              className="form-control ps-5"
              placeholder="Search by Username, Email, or Phone"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
            />
          </div>
{/* 
          <div className="filter-dropdown d-flex align-items-center gap-2">
            <Filter size={18} className="text-muted" />
            <select
              className="form-select"
              value={statusFilter}
              onChange={(e) => setStatusFilter(e.target.value)}
            >
              <option value="all">All Status</option>
              <option value="active">Active</option>
              <option value="inactive">Inactive</option>
            </select>
          </div> */}
        </div>

        {/* Table */}
        <div className="card">
          <div className="table-container">
            {filteredUsers.length === 0 ? (
              <div className="empty-state">
                <UsersIcon size={48} />
                <h3>No users found</h3>
                <p>Try different search or filters</p>
              </div>
            ) : (
              <table className="table">
                <thead>
                  <tr>
                    <th>User Info</th>
                    <th>Contact</th>
                    <th>Details</th>
                    <th>Registered</th>
                    {/* <th>Status</th>
                    <th>Action</th> */}
                  </tr>
                </thead>
                <tbody>
                  {filteredUsers.map((user) => (
                    <tr key={user._id}>
                      <td>
                        <strong>{user.username}</strong>
                        <div>ID: {user._id.slice(-8)}</div>
                      </td>
                      <td>
                        <div>
                          <Mail size={14} /> {user.email}
                        </div>
                        <div>
                          <Phone size={14} /> {user.phone || "N/A"}
                        </div>
                      </td>
                      <td>
                        <div>
                          <Cake size={14} /> {formatDate(user.dob)} (
                          {calculateAge(user.dob)} yrs)
                        </div>
                        <div>
                          <User size={14} />{" "}
                          <span className={getGenderBadge(user.gender)}>
                            {user.gender}
                          </span>
                        </div>
                      </td>
                      <td>{formatDate(user.createdAt)}</td>
                   {/* <td>
                        <span className={getStatusBadge(user.status)}>
                          {user.status || "active"}
                        </span>
                      </td> */}
                      {/* <td>
                        <button
                          className="btn btn-danger btn-sm"
                          onClick={() => handleDeleteUser(user._id)}
                        >
                          <Trash2 size={14} />
                        </button>
                      </td> */}
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Users;

// src/app/pages/admin/users.component.ts
import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../services/api.service';

interface User {
  _id: string;
  username: string;
  email: string;
  phone: string;
  dob: string;
  gender: string;
  createdAt: string;
  status?: string;
}

@Component({
  selector: 'app-users',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './users.component.html',
  styleUrls: ['./users.component.css']
})
export class UsersComponent implements OnInit {
  users: User[] = [];
  filteredUsers: User[] = [];
  searchTerm: string = "";
  statusFilter: string = "all";
  loading: boolean = false;
  error: string | null = null;

  constructor(
    private apiService: ApiService,
    private cdr: ChangeDetectorRef
  ) {}

  ngOnInit() {
    // Reset state when component initializes
    this.loading = false;
    this.error = null;
    this.users = [];
    this.filteredUsers = [];
    
    // Fetch users immediately - ensure it happens
    this.fetchUsers();
  }

  fetchUsers() {
    this.loading = false;
    this.error = null;
    
    // Ensure we're making the request
    const request = this.apiService.get<User[]>('api/admin/users', true);
    
    request.subscribe({
      next: (data) => {
        this.users = data || [];
        this.applyFilters();
        this.cdr.detectChanges();
      },
      error: (err) => {
        console.error("Error fetching users:", err);
        this.error = "Failed to fetch users. Check connection.";
        this.users = [];
        this.filteredUsers = [];
        this.cdr.detectChanges();
      }
    });
  }

  applyFilters() {
    let filtered = this.users;

    if (this.searchTerm) {
      const term = this.searchTerm.toLowerCase();
      filtered = filtered.filter(
        (user) =>
          (user.username?.toLowerCase() || "").includes(term) ||
          (user.email?.toLowerCase() || "").includes(term) ||
          (user.phone?.toLowerCase() || "").includes(term)
      );
    }

    if (this.statusFilter !== "all") {
      filtered = filtered.filter(
        (user) => (user.status || "active").toLowerCase() === this.statusFilter
      );
    }

    this.filteredUsers = filtered;
  }

  calculateAge(dob: string): number {
    if (!dob) return 0;
    const today = new Date();
    const birthDate = new Date(dob);
    let age = today.getFullYear() - birthDate.getFullYear();
    const m = today.getMonth() - birthDate.getMonth();
    if (m < 0 || (m === 0 && today.getDate() < birthDate.getDate())) age--;
    return age;
  }

  getGenderBadge(gender: string): string {
    const genderClasses: { [key: string]: string } = {
      male: "status-badge status-male",
      female: "status-badge status-female",
      other: "status-badge status-other",
    };
    return genderClasses[gender?.toLowerCase()] || "status-badge";
  }

  get totalUsersCount(): number {
    return this.users.length;
  }

  get activeUsersCount(): number {
    return this.users.filter(u => (u.status || "active").toLowerCase() === 'active').length;
  }

  get newThisMonthCount(): number {
    const now = new Date();
    return this.users.filter(u => {
      const d = new Date(u.createdAt);
      return d.getMonth() === now.getMonth() && d.getFullYear() === now.getFullYear();
    }).length;
  }

  get thisWeekCount(): number {
    const weekAgo = new Date();
    weekAgo.setDate(weekAgo.getDate() - 7);
    return this.users.filter(u => new Date(u.createdAt) >= weekAgo).length;
  }
}

<div class="container">
  <div class="users-container">
    <div class="page-header">
      <h1>Users Management</h1>
      <p>Manage all registered users</p>
    </div>
    <hr />

    <div *ngIf="error" class="error-message">
      <p>{{error}}</p>
    </div>

    <div *ngIf="!error">
      <!-- Stats Cards -->
      <div class="stats-grid">
        <div class="stat-card">
          <div class="stat-header">
            <span>Total Users</span>
            <div class="stat-icon bg-blue">
              <i class="fas fa-users"></i>
            </div>
          </div>
          <div class="stat-value">{{totalUsersCount}}</div>
        </div>

        <div class="stat-card">
          <div class="stat-header">
            <span>Active Users</span>
            <div class="stat-icon bg-green">
              <i class="fas fa-user"></i>
            </div>
          </div>
          <div class="stat-value">{{activeUsersCount}}</div>
        </div>

        <div class="stat-card">
          <div class="stat-header">
            <span>New This Month</span>
            <div class="stat-icon bg-yellow">
              <i class="fas fa-calendar"></i>
            </div>
          </div>
          <div class="stat-value">{{newThisMonthCount}}</div>
        </div>

        <div class="stat-card">
          <div class="stat-header">
            <span class="stat-title fw-bold">Registration Trend</span>
            <div class="stat-icon" style="background-color: #6b7280">
              <i class="fas fa-chart-line"></i>
            </div>
          </div>
          <div class="state">
            <div style="font-size: 0.8rem; color: #374151; marginTop: 4px">
              <div>This Week: {{thisWeekCount}}</div>
              <div>This Month: {{newThisMonthCount}}</div>
            </div>
          </div>
        </div>
      </div>

      <!-- Search & Filter -->
      <div class="search-filter-container">
        <div class="search-input position-relative flex-grow-1">
          <i class="fas fa-search search-icon position-absolute"
             style="top: 50%; left: 15px; transform: translateY(-50%)"></i>
          <input
            type="text"
            class="form-control ps-5"
            placeholder="Search by Username, Email, or Phone"
            [(ngModel)]="searchTerm"
            (ngModelChange)="applyFilters()"
          />
        </div>
      </div>

      <!-- Table -->
      <div class="card">
        <div class="table-container">
          <div *ngIf="filteredUsers.length === 0" class="empty-state">
            <i class="fas fa-users-slash fa-3x mb-3"></i>
            <h3>No users found</h3>
            <p>Try different search or filters</p>
          </div>
          
          <table *ngIf="filteredUsers.length > 0" class="table">
            <thead>
              <tr>
                <th>User Info</th>
                <th>Contact</th>
                <th>Details</th>
                <th>Registered</th>
              </tr>
            </thead>
            <tbody>
              <tr *ngFor="let user of filteredUsers">
                <td>
                  <strong>{{user.username}}</strong>
                  <div>ID: {{user._id.slice(-8)}}</div>
                </td>
                <td>
                  <div>
                    <i class="fas fa-envelope fa-xs"></i> {{user.email}}
                  </div>
                  <div>
                    <i class="fas fa-phone fa-xs"></i> {{user.phone || "N/A"}}
                  </div>
                </td>
                <td>
                  <div>
                    <i class="fas fa-birthday-cake fa-xs"></i> {{user.dob | date}} ({{calculateAge(user.dob)}} yrs)
                  </div>
                  <div>
                    <i class="fas fa-user fa-xs"></i> 
                    <span [class]="getGenderBadge(user.gender)">
                      {{user.gender}}
                    </span>
                  </div>
                </td>
                <td>{{user.createdAt | date}}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
