// src/Navbar.jsx
import React, { useState } from "react";
import { NavLink, Link, useNavigate, useLocation } from "react-router-dom"; // <-- Link add કર્યું
import "./css/Navbar.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faMagnifyingGlass } from "@fortawesome/free-solid-svg-icons";

const Navbar = ({ username, setUsername }) => {
  const [searchText, setSearchText] = useState("");
  const navigate = useNavigate();
  const location = useLocation();

  const handleSearchSubmit = (e) => {
    e.preventDefault();
    if (searchText.trim() !== "") {
      const currentPath = location.pathname;
      navigate(`${currentPath}?q=${encodeURIComponent(searchText)}`);
    }
  };

  const handleLogout = async () => {
    try {
      const token = localStorage.getItem('token');
      if (token) {
        await fetch('https://backend-t19q.onrender.com/logout', {
          method: 'POST',
          headers: { Authorization: `Bearer ${token}` },
        });
      }
    } finally {
      localStorage.removeItem('token');
      localStorage.removeItem('username');
      setUsername('');
      navigate('/home');
    }
  };

  const hideNavbarPaths = ["/order-success"];
  const shouldHideNavbar = hideNavbarPaths.includes(location.pathname);
  if (shouldHideNavbar) return null;

  return (
    <nav className="navbar navbar-expand-lg navbar-light bg-whitesmoke sticky-top">
      <div className="container">
        <Link className="navbar-brand d-flex" to="/">
          <img src="https://www.starbucks.in/assets/icon/logo.png" alt="" width="50" height="50" />
          <h3 className="fs-4 ms-1">Starbucks</h3>
        </Link>

        <button
          className="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
        >
          <span className="navbar-toggler-icon"></span>
        </button>

        <div className="collapse navbar-collapse" id="navbarSupportedContent">
          <ul className="navbar-nav me-auto ms-3 gap-5 nav-links">
            <li className="nav-item">
              <NavLink
                to="/"
                className={({ isActive }) =>
                  `nav-link underline-animate ${isActive ? 'active' : ''}`
                }
              >
                Home
              </NavLink>
            </li>
            <li className="nav-item">
              <NavLink
                to="/gift"
                className={({ isActive }) =>
                  `nav-link underline-animate ${isActive ? 'active' : ''}`
                }
              >
                Gift
              </NavLink>
            </li>
            <li className="nav-item">
              <NavLink
                to="/menu"
                className={({ isActive }) =>
                  `nav-link underline-animate ${isActive ? 'active' : ''}`
                }
              >
                Menu
              </NavLink>
            </li>
            <li className="nav-item">
              <NavLink
                to="/orders"
                className={({ isActive }) =>
                  `nav-link underline-animate ${isActive ? 'active' : ''}`
                }
              >
                Order
              </NavLink>
            </li>
          </ul>

          <form
            className="d-flex me-4 search-form mb-1"
            onSubmit={handleSearchSubmit}
          >
            <input
              className="me-2 search bg-transparent head1"
              type="search"
              placeholder="Search"
              id="search"
              value={searchText}
              autoComplete="off"
              autoCapitalize="words"
              autoCorrect="off"
              spellCheck={false}
              onChange={(e) => {
                const value = e.target.value;
                setSearchText(value);
                if (value.trim() === "") {
                  const currentPath = location.pathname;
                  navigate(`${currentPath}`);
                }
              }}
            />
            <button className="btn1 btn btn-success" type="submit">
              <FontAwesomeIcon icon={faMagnifyingGlass} />
            </button>
          </form>

          <div className="d-flex align-items-center">
            <Link to="/cart" className="btn2 btn btn-success me-3 mb-2">
              🛒 <strong>MyCart</strong>
            </Link>

            <div className="dropdown nav-item text-center mb-2">
              <a
                className="text-decoration-none dropdown-toggle fw-bold text-dark"
                href="#"
                role="button"
                data-bs-toggle="dropdown"
              >
                <i className="fas fa-user-circle"></i> Account
              </a>
              <ul className="dropdown-menu custom-dropdown">
                {username ? (
                  <>
                    <li className="dropdown-header text-success fw-bold">
                      <i className="fas fa-user me-2"></i> {username}
                    </li>
                    <li>
                      <hr className="dropdown-divider" />
                    </li>
                    <li>
                      <button
                        className="dropdown-item underline-animate"
                        onClick={handleLogout}
                      >
                        <i className="fas fa-sign-out-alt me-2"></i> Logout
                      </button>
                    </li>
                  </>
                ) : (
                  <>
                    <li>
                      <Link
                        className="dropdown-item underline-animate"
                        to="/login"
                      >
                        <i className="fas fa-sign-in-alt me-2"></i> Login
                      </Link>
                    </li>
                    <li>
                      <Link
                        className="dropdown-item underline-animate"
                        to="/register"
                      >
                        <i className="fas fa-user-plus me-2"></i> Sign-Up
                      </Link>
                    </li>
                  </>
                )}
              </ul>
            </div>
          </div>
        </div>
      </div>
    </nav>
  );
};

export default Navbar;

// src/app/components/navbar.component.ts
import { Component, OnInit, PLATFORM_ID, inject } from '@angular/core';
import { CommonModule, isPlatformBrowser } from '@angular/common';
import { Router, RouterModule, NavigationEnd } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { faMagnifyingGlass } from '@fortawesome/free-solid-svg-icons';
import { AuthService } from '../services/auth.service';
import { HttpClient } from '@angular/common/http';
import { filter } from 'rxjs/operators';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule, RouterModule, FormsModule, FontAwesomeModule],
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent implements OnInit {
  username: string = '';
  searchText: string = '';
  faMagnifyingGlass = faMagnifyingGlass;
  shouldHideNavbar: boolean = false;
  private platformId = inject(PLATFORM_ID);

  private hideNavbarPaths = ["/order-success"];

  constructor(
    private authService: AuthService,
    private router: Router,
    private http: HttpClient
  ) {}

  ngOnInit() {
    this.authService.username$.subscribe(name => {
      this.username = name;
    });

    this.router.events.pipe(
      filter(event => event instanceof NavigationEnd)
    ).subscribe((event: any) => {
      this.shouldHideNavbar = this.hideNavbarPaths.includes(event.urlAfterRedirects);
    });
  }

  handleSearchSubmit(e?: Event) {
    if (e) e.preventDefault();
    if (this.searchText.trim() !== "") {
      const currentPath = this.router.url.split('?')[0];
      this.router.navigate([currentPath], { queryParams: { q: this.searchText } });
    }
  }

  onSearchChange() {
    if (this.searchText.trim() === "") {
      const currentPath = this.router.url.split('?')[0];
      this.router.navigate([currentPath]);
    }
  }

  async handleLogout() {
    try {
      if (isPlatformBrowser(this.platformId)) {
        const token = localStorage.getItem('token');
        if (token) {
          await this.http.post('http://localhost:3001/logout', {}, {
            headers: { Authorization: `Bearer ${token}` }
          }).toPromise();
        }
      }
    } catch (error) {
      console.error('Logout error', error);
    } finally {
      this.authService.logout();
      this.router.navigate(['/home']);
    }
  }
}

<nav *ngIf="!shouldHideNavbar" class="navbar navbar-expand-lg navbar-light bg-whitesmoke sticky-top">
  <div class="container">
    <a class="navbar-brand d-flex" routerLink="/">
      <img src="https://www.starbucks.in/assets/icon/logo.png" alt="" width="50" height="50" />
      <h3 class="ms-1">Starbucks</h3>
    </a>

    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto ms-3 gap-5 nav-links">
        <li class="nav-item">
          <a
            routerLink="/"
            routerLinkActive="active"
            [routerLinkActiveOptions]="{exact: true}"
            class="nav-link underline-animate"
          >
            Home
          </a>
        </li>
        <li class="nav-item">
          <a
            routerLink="/gift"
            routerLinkActive="active"
            class="nav-link underline-animate"
          >
            Gift
          </a>
        </li>
        <li class="nav-item">
          <a
            routerLink="/menu"
            routerLinkActive="active"
            class="nav-link underline-animate"
          >
            Menu
          </a>
        </li>
        <li class="nav-item">
          <a
            routerLink="/orders"
            routerLinkActive="active"
            class="nav-link underline-animate"
          >
            Order
          </a>
        </li>
      </ul>

      <form
        class="d-flex me-4 search-form mb-1"
        (submit)="handleSearchSubmit($event)"
      >
        <input
          class="me-2 search bg-transparent head1"
          type="search"
          placeholder="Search"
          id="search"
          name="searchText"
          [(ngModel)]="searchText"
          (ngModelChange)="onSearchChange()"
          autocomplete="off"
          autocapitalize="words"
          autocorrect="off"
          [spellcheck]="false"
        />
        <button class="btn1 btn btn-success" type="submit">
          <fa-icon [icon]="faMagnifyingGlass"></fa-icon>
        </button>
      </form>

      <div class="d-flex align-items-center">
        <a routerLink="/cart" class="btn2 btn btn-success me-3 mb-2">
          🛒 <strong>MyCart</strong>
        </a>

        <div class="dropdown nav-item text-center mb-2">
          <a
            class="text-decoration-none dropdown-toggle fw-bold text-dark"
            href="javascript:void(0)"
            role="button"
            data-bs-toggle="dropdown"
          >
            <i class="fas fa-user-circle"></i> Account
          </a>
          <ul class="dropdown-menu custom-dropdown">
            <ng-container *ngIf="username; else guestLinks">
              <li class="dropdown-header text-success fw-bold">
                <i class="fas fa-user me-2"></i> {{username}}
              </li>
              <li>
                <hr class="dropdown-divider" />
              </li>
              <li>
                <button
                  class="dropdown-item underline-animate"
                  (click)="handleLogout()"
                >
                  <i class="fas fa-sign-out-alt me-2"></i> Logout
                </button>
              </li>
            </ng-container>
            <ng-template #guestLinks>
              <li>
                <a
                  class="dropdown-item underline-animate"
                  routerLink="/login"
                >
                  <i class="fas fa-sign-in-alt me-2"></i> Login
                </a>
              </li>
              <li>
                <a
                  class="dropdown-item underline-animate"
                  routerLink="/register"
                >
                  <i class="fas fa-user-plus me-2"></i> Sign-Up
                </a>
              </li>
            </ng-template>
          </ul>
        </div>
      </div>
    </div>
  </div>
</nav>
