// src/app/pages/admin/admin-login.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { ApiService } from '../../services/api.service';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-admin-login',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './admin-login.component.html',
  styleUrls: ['./admin-login.component.css']
})
export class AdminLoginComponent implements OnInit {
  username = "";
  password = "";
  error = "";
  loading = false;

  constructor(
    private router: Router,
    private apiService: ApiService,
    private authService: AuthService
  ) {}

  ngOnInit() {
    if (this.authService.isAdmin) {
      this.router.navigate(['/admin/dashboard'], { replaceUrl: true });
    }
  }

  handleSubmit() {
    this.loading = true;
    this.error = "";
    this.apiService.post<any>('api/admin/login', {
      username: this.username,
      password: this.password,
    }).subscribe({
      next: (res) => {
        if (res.success) {
          this.authService.setAdminToken(res.token);
          this.router.navigate(['/admin/dashboard']);
        } else {
          this.error = res.message || "Login failed";
        }
      },
      error: () => {
        this.error = "Server error";
      },
      complete: () => {
        this.loading = false;
      }
    });
  }
}

<div class="body">
  <div class="container d-flex justify-content-center align-items-center vh-100">
    <div class="login-container">
      <div class="text-center mb-3">
        <div
          class="bg-success rounded-circle d-inline-flex align-items-center justify-content-center mb-4"
          style="width: 60px; height: 60px"
        >
          <i class="fas fa-shield-alt text-white fs-3"></i>
        </div>
        <h5 class="h2 text-success h3 fw-bold fs-2">Admin Login</h5>
        <p class="text-muted small mb-0 fw-bold p">
          Access your admin dashboard
        </p>
      </div>
      <form (ngSubmit)="handleSubmit()">
        <div class="mb-3">
          <label class="form-label fw-medium">Username</label>
          <input
            type="text"
            name="username"
            class="form-control form-control-lg"
            [(ngModel)]="username"
            placeholder="Enter your username"
            required
          />
        </div>

        <div class="mb-3">
          <label class="form-label fw-medium">Password</label>
          <input
            type="password"
            name="password"
            class="form-control form-control-lg"
            [(ngModel)]="password"
            placeholder="Enter your password"
            required
          />
        </div>

        <div *ngIf="error" class="alert alert-danger py-2 mb-3">
          <span>{{error}}</span>
        </div>

        <button
          type="submit"
          class="btn btn-success btn-lg w-100 fw-bold"
          [disabled]="loading"
        >
          <span *ngIf="loading"
            class="spinner-border spinner-border-sm me-2"
            role="status"
            aria-hidden="true"
          ></span>
          {{ loading ? 'Logging in...' : 'Login' }}
        </button>
      </form>
      <div class="text-center mt-3">
        <small class="text-muted fw-bold">
          Secure admin access only
        </small>
      </div>
    </div>
  </div>
</div>

// src/admin/AdminLogin.jsx
import React, { useState, useEffect } from "react";
import axios from "axios";
import "bootstrap/dist/css/bootstrap.min.css";
import { useNavigate } from "react-router-dom";

const AdminLogin = () => {
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();

  // Check if admin is already logged in
  useEffect(() => {
    const adminToken = localStorage.getItem("adminToken");
    if (adminToken) {
      navigate("/admin/dashboard", { replace: true });
    }
  }, [navigate]);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError("");
    try {
      const res = await axios.post("https://backend-t19q.onrender.com/admin/login", {
        username,
        password,
      });
      if (res.data.success) {
        localStorage.setItem("adminToken", res.data.token);
        navigate("/admin/dashboard");
      } else {
        setError(res.data.message || "Login failed");
      }
    } catch {
      setError("Server error");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="body">
      <div className="container d-flex justify-content-center align-items-center vh-100">
        <div className="login-container">
          <div className="text-center mb-3">
            <div
              className="bg-success rounded-circle d-inline-flex align-items-center justify-content-center mb-4"
              style={{ width: "60px", height: "60px" }}
            >
              <i className="fas fa-shield-alt text-white fs-3"></i>
            </div>
            <h5 className="h2 text-success">Admin Login</h5>
            <p className="text-muted small mb-0 fw-bold">
              Access your admin dashboard
            </p>
          </div>
          <form onSubmit={handleSubmit}>
            <div className="mb-3">
              <label className="form-label fw-medium">Username</label>
              <input
                type="text"
                className="form-control form-control-lg"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                placeholder="Enter your username"
                required
              />
            </div>

            <div className="mb-3">
              <label className="form-label fw-medium">Password</label>
              <input
                type="password"
                className="form-control form-control-lg"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                placeholder="Enter your password"
                required
              />
            </div>

            {error && (
              <div className="alert alert-danger py-2 mb-3">
                <span>{error}</span>
              </div>
            )}

            <button
              type="submit"
              className="btn btn-success btn-lg w-100 fw-bold"
              disabled={loading}
            >
              {loading ? (
                <>
                  <span
                    className="spinner-border spinner-border-sm me-2"
                    role="status"
                    aria-hidden="true"
                  ></span>
                  Logging in...
                </>
              ) : (
                "Login"
              )}
            </button>
          </form>
          <div className="text-center mt-3">
            <small className="text-muted fw-bold">
              Secure admin access only
            </small>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AdminLogin;
