// src/app/pages/admin/dashboard.component.ts
import { Component, OnInit, ChangeDetectorRef, PLATFORM_ID, inject } from '@angular/core';
import { CommonModule, isPlatformBrowser } from '@angular/common';
import { Router } from '@angular/router';
import { ApiService } from '../../services/api.service';

interface DashboardStats {
  totalUsers: number;
  totalOrders: number;
  totalRevenue: number;
}

interface RecentOrder {
  _id: string;
  orderId: string;
  username: string;
  total: number;
  status: string;
  createdAt: string;
}

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css']
})
export class DashboardComponent implements OnInit {
  stats: DashboardStats = {
    totalUsers: 0,
    totalOrders: 0,
    totalRevenue: 0
  };
  recentOrders: RecentOrder[] = [];
  loading: boolean = false;
  error: string | null = null;

  private platformId = inject(PLATFORM_ID);

  constructor(
    private apiService: ApiService,
    private cdr: ChangeDetectorRef,
    private router: Router
  ) {}

  ngOnInit() {
    // Reset state when component initializes
    this.loading = false;
    this.error = null;
    this.stats = {
      totalUsers: 0,
      totalOrders: 0,
      totalRevenue: 0
    };
    this.recentOrders = [];
    
    // Always try to fetch dashboard data - let API call determine authentication
    this.fetchDashboardData();
  }

  fetchDashboardData() {
    // Clear any previous errors
    this.error = null;
    
    // Make the API request immediately
    const request = this.apiService.get<any>('api/admin/stats', true);
    
    // Subscribe to the request
    request.subscribe({
      next: (res) => {
        if (res) {
          this.stats = {
            totalUsers: res.totalUsers || 0,
            totalOrders: res.totalOrders || 0,
            totalRevenue: res.totalRevenue || 0
          };
          this.recentOrders = res.recentOrders || [];
        }
        this.cdr.detectChanges();
      },
      error: (err) => {
        console.error('Error fetching dashboard data:', err);
        
        // Check if error is due to authentication issues
        if (err.status === 401 || err.status === 403) {
          // Token is invalid/expired, redirect to login
          this.router.navigate(['/admin/login']);
          return;
        }
        
        // Only show error message for real server/network issues
        this.error = "Failed to load dashboard data. Please try again later.";
        this.stats = {
          totalUsers: 0,
          totalOrders: 0,
          totalRevenue: 0
        };
        this.recentOrders = [];
        this.cdr.detectChanges();
      }
    });
  }

  getStatusBadge(status: string): string {
    const statusClasses: { [key: string]: string } = {
      completed: 'status-completed',
      pending: 'status-pending',
      cancelled: 'status-cancelled',
      Approved: 'status-completed',
      Cancelled: 'status-cancelled',
    };
    return `status-badge ${statusClasses[status] || 'status-pending'}`;
  }
}

<div class="container dashboard-root">
  <div class="page-header">
    <h1 class="page-title">Dashboard</h1>
    <p class="page-subtitle">Welcome to your admin dashboard</p>
  </div>
  <hr/>
  <hr class="dashboard-hr" />

  <!-- Error State -->
  <div *ngIf="error" class="alert alert-danger text-center">
    {{error}}
  </div>

  <div *ngIf="!error" class="page-content">
    <!-- Stats -->
    <div class="stats-grid">
      <div class="stat-card">
        <div class="stat-header">
          <span class="stat-title">Total Users</span>
          <div class="stat-icon" style="background-color: #3b82f6">
            <i class="fas fa-users"></i>
          </div>
        </div>
        <div class="stat-value">{{stats.totalUsers | number}}</div>
      </div>

      <div class="stat-card">
        <div class="stat-header">
          <span class="stat-title">Total Orders</span>
          <div class="stat-icon" style="background-color: #10b981">
            <i class="fas fa-shopping-cart"></i>
          </div>
        </div>
        <div class="stat-value">{{stats.totalOrders | number}}</div>
      </div>

      <div class="stat-card">
        <div class="stat-header">
          <span class="stat-title">Total Revenue</span>
          <div class="stat-icon" style="background-color: #f59e0b">
            <i class="fas fa-dollar-sign"></i>
          </div>
        </div>
        <div class="stat-value">₹{{stats.totalRevenue | number}}</div>
      </div>
    </div>

    <!-- Recent Orders -->
    <div class="card">
      <div class="card-header">
        <h2 class="card-title">Recent Orders</h2>
      </div>
      <div class="order-table-container">
        <p *ngIf="recentOrders.length === 0" class="no-orders">No recent orders.</p>
        <table *ngIf="recentOrders.length > 0" class="order-table">
          <thead>
            <tr>
              <th>Order ID</th>
              <th>Customer</th>
              <th>Total</th>
              <th>Status</th>
              <th>Date</th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let order of recentOrders">
              <td>{{order.orderId}}</td>
              <td>{{order.username}}</td>
              <td>₹{{order.total}}</td>
              <td>
                <span [class]="getStatusBadge(order.status)">{{order.status}}</span>
              </td>
              <td>{{order.createdAt | date}}</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

// src/admin/Dashboard.jsx
import { useState, useEffect } from 'react';
import { Users, ShoppingCart, DollarSign, Activity } from 'lucide-react';
import axios from 'axios';
import './Dashboard.css';

const Dashboard = () => {
  const [stats, setStats] = useState({
    totalUsers: 0,
    totalOrders: 0,
    totalRevenue: 0,
  });
  const [recentOrders, setRecentOrders] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchDashboardData = async () => {
      try {
        const token = localStorage.getItem('adminToken');
        if (!token) {
          console.error('No admin token found');
          return;
        }

        const response = await axios.get('https://backend-t19q.onrender.com/api/admin/stats', {
          headers: { Authorization: `Bearer ${token}` },
        });

        const { totalUsers, totalOrders, totalRevenue, recentOrders } = response.data;
        setStats({ totalUsers, totalOrders, totalRevenue });
        setRecentOrders(recentOrders);
      } catch (error) {
        console.error('Error fetching dashboard data:', error);
      } finally {
        setLoading(false);
      }
    };

    fetchDashboardData();
  }, []);

  const getStatusBadge = (status) => {
    const statusClasses = {
      completed: 'status-completed',
      pending: 'status-pending',
      cancelled: 'status-cancelled',
      Approved: 'status-completed',
      Cancelled: 'status-cancelled',
    };
    return `status-badge ${statusClasses[status] || 'status-pending'}`;
  };

  if (loading) {
    return (
      <div className="dashboard-root">
        <div className="loading">
          <Activity className="animate-spin" size={24} />
          <span style={{ marginLeft: '0.5rem' }}>Loading dashboard...</span>
        </div>
      </div>
    );
  }

  return (
    <div className="container dashboard-root">
      <div className="page-header">
        <h1 className="page-title">Dashboard</h1>
        <p className="page-subtitle">Welcome to your admin dashboard</p>
      </div>
      <hr/>
      {/* small, controlled hr */}
      <hr className="dashboard-hr" />

      <div className="page-content">
        {/* Stats */}
        <div className="stats-grid">
          <div className="stat-card">
            <div className="stat-header">
              <span className="stat-title">Total Users</span>
              <div className="stat-icon" style={{ backgroundColor: '#3b82f6' }}>
                <Users size={20} />
              </div>
            </div>
            <div className="stat-value">{stats.totalUsers.toLocaleString()}</div>
          </div>

          <div className="stat-card">
            <div className="stat-header">
              <span className="stat-title">Total Orders</span>
              <div className="stat-icon" style={{ backgroundColor: '#10b981' }}>
                <ShoppingCart size={20} />
              </div>
            </div>
            <div className="stat-value">{stats.totalOrders.toLocaleString()}</div>
          </div>

          <div className="stat-card">
            <div className="stat-header">
              <span className="stat-title">Total Revenue</span>
              <div className="stat-icon" style={{ backgroundColor: '#f59e0b' }}>
                <DollarSign size={20} />
              </div>
            </div>
            <div className="stat-value">₹{stats.totalRevenue.toLocaleString()}</div>
          </div>
        </div>

        {/* Recent Orders */}
        <div className="card">
          <div className="card-header">
            <h2 className="card-title">Recent Orders</h2>
          </div>
          <div className="order-table-container">
            {recentOrders.length === 0 ? (
              <p className="no-orders">No recent orders.</p>
            ) : (
              <table className="order-table">
                <thead >
                  <tr>
                    <th>Order ID</th>
                    <th>Customer</th>
                    <th>Total</th>
                    <th>Status</th>
                    <th>Date</th>
                  </tr>
                </thead>
                <tbody>
                  {recentOrders.map((order) => (
                    <tr key={order._id}>
                      <td>{order.orderId}</td>
                      <td>{order.username}</td>
                      <td>₹{order.total}</td>
                      <td>
                        <span className={getStatusBadge(order.status)}>{order.status}</span>
                      </td>
                      <td>{new Date(order.createdAt).toLocaleDateString()}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default Dashboard;
