// src/app/pages/cart.component.ts
import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';
import { ApiService } from '../services/api.service';
import { HttpErrorResponse } from '@angular/common/http';

interface CartItem {
  productId: string;
  title: string;
  price: number;
  image: string;
  quantity: number;
  total: number;
}

@Component({
  selector: 'app-cart',
  standalone: true,
  imports: [CommonModule, RouterModule],
  templateUrl: './cart.component.html',
  styleUrls: ['./cart.component.css']
})
export class CartComponent implements OnInit {
  cartItems: CartItem[] = [];
  totalAmount: number = 0;
  error: string | null = null;

  constructor(
    private apiService: ApiService,
    private router: Router,
    private cdr: ChangeDetectorRef
  ) {}

  ngOnInit() {
    // Reset state when component initializes
    this.cartItems = [];
    this.totalAmount = 0;
    this.error = null;
    
    // Fetch cart immediately - ensure it happens
    this.fetchCart();
  }

  fetchCart() {
    this.error = null;
    
    // Ensure we're making the request
    const request = this.apiService.get<{ cart: CartItem[] }>('api/cart/cart');
    
    request.subscribe({
      next: (res) => {
        this.cartItems = res.cart || [];
        this.totalAmount = this.cartItems.reduce((sum, item) => sum + item.total, 0);
        this.cdr.detectChanges();
      },
      error: (err: HttpErrorResponse) => {
        console.error("Error fetching cart:", err);
        
        if (err.status === 401) {
          // Unauthorized - redirect to login
          alert("Please login to view your cart");
          this.router.navigate(['/login']);
        } else {
          this.error = "Failed to load cart. Please try again later.";
        }
        this.cartItems = [];
        this.totalAmount = 0;
        this.cdr.detectChanges();
      }
    });
  }

  updateQuantity(productId: string, action: 'increase' | 'decrease') {
    const request = this.apiService.put(`api/cart/update-quantity/${productId}`, { action });
    
    request.subscribe({
      next: () => {
        this.fetchCart();
      },
      error: (err) => {
        console.error("Failed to update quantity:", err);
        alert("Failed to update quantity. Please try again.");
      }
    });
  }

  removeFromCart(productId: string) {
    const request = this.apiService.delete(`api/cart/remove-from-cart/${productId}`);
    
    request.subscribe({
      next: () => {
        this.fetchCart();
      },
      error: (err) => {
        console.error("Failed to remove item:", err);
        alert("Failed to remove item. Please try again.");
      }
    });
  }
}

<div class="container mt-5">
  <!-- Error State -->
  <div *ngIf="error" class="alert alert-danger text-center">
    {{error}}
  </div>

  <!-- Empty State (only show when no error) -->
  <div *ngIf="!error && cartItems.length === 0" class="alert alert-warning text-center fw-bold fs-5">
    🛒 Your cart is empty.
  </div>

  <div *ngIf="!error && cartItems.length > 0" class="row justify-content-center">
    <div class="col-lg-11">
      <div class="table-responsive card-custom">
        <table class="table table-bordered align-middle text-center shadow-sm ">
          <thead class="table">
            <tr class="tr">
              <th>Image</th>
              <th>Title</th>
              <th>Price</th>
              <th>Qty</th>
              <th>Total</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <tr *ngFor="let item of cartItems">
              <td>
                <img [src]="item.image" [alt]="item.title" width="60" class="img-fluid rounded" />
              </td>
              <td>{{ item.title }}</td>
              <td>₹{{ item.price }}</td>
              <td>
                <div class="d-flex justify-content-center align-items-center gap-2">
                  <button (click)="updateQuantity(item.productId, 'decrease')" class="btn btn-outline-danger btn-sm">
                    −
                  </button>
                  <span class="fw-bold">{{ item.quantity }}</span>
                  <button (click)="updateQuantity(item.productId, 'increase')" class="btn btn-outline-success btn-sm">
                    +
                  </button>
                </div>
              </td>
              <td>₹{{ item.total }}</td>
              <td>
                <button (click)="removeFromCart(item.productId)" class="btn btn-danger btn-sm btn-remove">
                  Remove
                </button>
              </td>
            </tr>

            <!-- Total Amount Row -->
            <tr>
              <td colSpan="4" class="text-end fw-bold">
                Total:
              </td>
              <td class="text-success fw-bold fs-5">
                ₹{{ totalAmount }}
              </td>
              <td class="text-center">
                <a routerLink="/checkout" class="btn btn-success btn-md btn-order">
                  Order Now
                </a>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

// src/Cart.jsx
import React, { useEffect, useState } from "react";
import axios from "axios";
import "./css/Cart.css";
import { Link } from "react-router-dom";

const Cart = () => {
  const [cartItems, setCartItems] = useState([]);
  const [totalAmount, setTotalAmount] = useState(0);

  useEffect(() => {
    fetchCart();
  }, []);

  const fetchCart = async () => {
    try {
      const token = localStorage.getItem("token");
      const res = await axios.get("https://backend-t19q.onrender.com/cart", {
        headers: { Authorization: `Bearer ${token}` },
      });
      const cart = res.data.cart || [];
      setCartItems(cart);
      const total = cart.reduce((sum, item) => sum + item.total, 0);
      setTotalAmount(total);
    } catch (err) {
      console.error("Error fetching cart:", err);
    }
  };

  const updateQuantity = async (productId, action) => {
    try {
      const token = localStorage.getItem("token");
      await axios.put(
        `https://backend-t19q.onrender.com/update-quantity/${productId}`,
        { action },
        { headers: { Authorization: `Bearer ${token}` } }
      );
      fetchCart();
    } catch (err) {
      console.error("Failed to update quantity:", err);
    }
  };

  const removeFromCart = async (productId) => {
    try {
      const token = localStorage.getItem("token");
      await axios.delete(
        `https://backend-t19q.onrender.com/remove-from-cart/${productId}`,
        {
          headers: { Authorization: `Bearer ${token}` },
        }
      );
      fetchCart();
    } catch (err) {
      console.error("Failed to remove item:", err);
    }
  };

  return (
    <div className="container mt-5">
      {cartItems.length === 0 ? (
        <div className="alert alert-warning text-center fw-bold fs-5">
          🛒 Your cart is empty.
        </div>
      ) : (
        <div className="row justify-content-center">
          <div className="col-lg-11">
            <div className="table-responsive card-custom">
              <table className="table table-bordered align-middle text-center shadow-sm ">
                <thead className="table">
                  <tr className="tr">
                    <th>Image</th>
                    <th>Title</th>
                    <th>Price</th>
                    <th>Qty</th>
                    <th>Total</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  {cartItems.map((item) => (
                    <tr key={item.productId}>
                      <td>
                        <img
                          src={item.image}
                          alt={item.title}
                          width="60"
                          className="img-fluid rounded"
                        />
                      </td>
                      <td>{item.title}</td>
                      <td>₹{item.price}</td>
                      <td>
                        <div className="d-flex justify-content-center align-items-center gap-2">
                          <button
                            onClick={() =>
                              updateQuantity(item.productId, "decrease")
                            }
                            className="btn btn-outline-danger btn-sm"
                          >
                            −
                          </button>
                          <span className="fw-bold">{item.quantity}</span>
                          <button
                            onClick={() =>
                              updateQuantity(item.productId, "increase")
                            }
                            className="btn btn-outline-success btn-sm"
                          >
                            +
                          </button>
                        </div>
                      </td>
                      <td>₹{item.total}</td>
                      <td>
                        <button
                          onClick={() => removeFromCart(item.productId)}
                          className="btn btn-danger btn-sm btn-remove"
                        >
                          Remove
                        </button>
                      </td>
                    </tr>
                  ))}

                  {/* Total Amount Row */}
                  <tr>
                    <td colSpan="4" className="text-end fw-bold">
                      Total:
                    </td>
                    <td className="text-success fw-bold fs-5">
                      ₹{totalAmount}
                    </td>
                    <td className="text-center">
                      <Link
                        to="/checkout"
                        className="btn btn-success btn-md btn-order"
                      >
                        Order Now
                      </Link>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Cart;
